Introduce Jeandle compiler
Co-authored-by: Wei Tang <tangwei.tang@antgroup.com>
Co-authored-by: Xuejin He <hexuejin.hxj@antgroup.com>
Co-authored-by: Chao Wang <xiyun.wc@antgroup.com>
Co-authored-by: Sendao Yan <yansendao.ysd@alibaba-inc.com>
Co-authored-by: Qizheng Xing <xingqizheng.xqz@alibaba-inc.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,6 @@
 #
 # Copyright (c) 2022, 2024, Oracle and/or its affiliates. All rights reserved.
+# Copyright (c) 2025, the Jeandle-JDK Authors. All rights reserved.
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 #
 # This code is free software; you can redistribute it and/or modify it
@@ -26,16 +27,15 @@
 name: 'OpenJDK GHA Sanity Checks'
 
 on:
-  push:
-    branches-ignore:
-      - master
-      - pr/*
+  pull_request_target:
+    branches:
+      - 'main'
   workflow_dispatch:
     inputs:
       platforms:
-        description: 'Platform(s) to execute on (comma separated, e.g. "linux-x64, macos, aarch64")'
+        description: 'Platform(s) to execute on (comma separated, e.g. "linux-x64")'
         required: true
-        default: 'linux-x64, linux-x86-hs, linux-x64-variants, linux-cross-compile, macos-x64, macos-aarch64, windows-x64, windows-aarch64, docs'
+        default: 'linux-x64'
       configure-arguments:
         description: 'Additional configure arguments'
         required: false
@@ -58,14 +58,6 @@ jobs:
     runs-on: ubuntu-22.04
     outputs:
       linux-x64: ${{ steps.include.outputs.linux-x64 }}
-      linux-x86-hs: ${{ steps.include.outputs.linux-x86-hs }}
-      linux-x64-variants: ${{ steps.include.outputs.linux-x64-variants }}
-      linux-cross-compile: ${{ steps.include.outputs.linux-cross-compile }}
-      macos-x64: ${{ steps.include.outputs.macos-x64 }}
-      macos-aarch64: ${{ steps.include.outputs.macos-aarch64 }}
-      windows-x64: ${{ steps.include.outputs.windows-x64 }}
-      windows-aarch64: ${{ steps.include.outputs.windows-aarch64 }}
-      docs: ${{ steps.include.outputs.docs }}
 
     steps:
       - name: 'Checkout the scripts'
@@ -122,14 +114,6 @@ jobs:
           }
 
           echo "linux-x64=$(check_platform linux-x64 linux x64)" >> $GITHUB_OUTPUT
-          echo "linux-x86-hs=$(check_platform linux-x86-hs linux x86)" >> $GITHUB_OUTPUT
-          echo "linux-x64-variants=$(check_platform linux-x64-variants variants)" >> $GITHUB_OUTPUT
-          echo "linux-cross-compile=$(check_platform linux-cross-compile cross-compile)" >> $GITHUB_OUTPUT
-          echo "macos-x64=$(check_platform macos-x64 macos x64)" >> $GITHUB_OUTPUT
-          echo "macos-aarch64=$(check_platform macos-aarch64 macos aarch64)" >> $GITHUB_OUTPUT
-          echo "windows-x64=$(check_platform windows-x64 windows x64)" >> $GITHUB_OUTPUT
-          echo "windows-aarch64=$(check_platform windows-aarch64 windows aarch64)" >> $GITHUB_OUTPUT
-          echo "docs=$(check_platform docs)" >> $GITHUB_OUTPUT
 
   ###
   ### Build jobs
@@ -146,157 +130,6 @@ jobs:
       make-arguments: ${{ github.event.inputs.make-arguments }}
     if: needs.prepare.outputs.linux-x64 == 'true'
 
-  build-linux-x86-hs:
-    name: linux-x86-hs
-    needs: prepare
-    uses: ./.github/workflows/build-linux.yml
-    with:
-      platform: linux-x86
-      make-target: 'hotspot'
-      gcc-major-version: '10'
-      gcc-package-suffix: '-multilib'
-      apt-architecture: 'i386'
-      # Some multilib libraries do not have proper inter-dependencies, so we have to
-      # install their dependencies manually.
-      apt-extra-packages: 'libfreetype-dev:i386 libtiff-dev:i386 libcupsimage2-dev:i386 libc6-i386 libgcc-s1:i386 libstdc++6:i386'
-      extra-conf-options: '--with-target-bits=32'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.linux-x86-hs == 'true'
-
-  build-linux-x64-hs-nopch:
-    name: linux-x64-hs-nopch
-    needs: prepare
-    uses: ./.github/workflows/build-linux.yml
-    with:
-      platform: linux-x64
-      make-target: 'hotspot'
-      debug-levels: '[ "debug" ]'
-      gcc-major-version: '10'
-      extra-conf-options: '--disable-precompiled-headers'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.linux-x64-variants == 'true'
-
-  build-linux-x64-hs-zero:
-    name: linux-x64-hs-zero
-    needs: prepare
-    uses: ./.github/workflows/build-linux.yml
-    with:
-      platform: linux-x64
-      make-target: 'hotspot'
-      debug-levels: '[ "debug" ]'
-      gcc-major-version: '10'
-      extra-conf-options: '--with-jvm-variants=zero --disable-precompiled-headers'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.linux-x64-variants == 'true'
-
-  build-linux-x64-hs-minimal:
-    name: linux-x64-hs-minimal
-    needs: prepare
-    uses: ./.github/workflows/build-linux.yml
-    with:
-      platform: linux-x64
-      make-target: 'hotspot'
-      debug-levels: '[ "debug" ]'
-      gcc-major-version: '10'
-      extra-conf-options: '--with-jvm-variants=minimal --disable-precompiled-headers'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.linux-x64-variants == 'true'
-
-  build-linux-x64-hs-optimized:
-    name: linux-x64-hs-optimized
-    needs: prepare
-    uses: ./.github/workflows/build-linux.yml
-    with:
-      platform: linux-x64
-      make-target: 'hotspot'
-      # Technically this is not the "debug" level, but we can't inject a new matrix state for just this job
-      debug-levels: '[ "debug" ]'
-      gcc-major-version: '10'
-      extra-conf-options: '--with-debug-level=optimized --disable-precompiled-headers'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.linux-x64-variants == 'true'
-
-  build-linux-cross-compile:
-    name: linux-cross-compile
-    needs: prepare
-    uses: ./.github/workflows/build-cross-compile.yml
-    with:
-      gcc-major-version: '10'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.linux-cross-compile == 'true'
-
-  build-macos-x64:
-    name: macos-x64
-    needs: prepare
-    uses: ./.github/workflows/build-macos.yml
-    with:
-      platform: macos-x64
-      runs-on: 'macos-13'
-      xcode-toolset-version: '14.3.1'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.macos-x64 == 'true'
-
-  build-macos-aarch64:
-    name: macos-aarch64
-    needs: prepare
-    uses: ./.github/workflows/build-macos.yml
-    with:
-      platform: macos-aarch64
-      runs-on: 'macos-14'
-      xcode-toolset-version: '15.4'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.macos-aarch64 == 'true'
-
-  build-windows-x64:
-    name: windows-x64
-    needs: prepare
-    uses: ./.github/workflows/build-windows.yml
-    with:
-      platform: windows-x64
-      msvc-toolset-version: '14.29'
-      msvc-toolset-architecture: 'x86.x64'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.windows-x64 == 'true'
-
-  build-windows-aarch64:
-    name: windows-aarch64
-    needs: prepare
-    uses: ./.github/workflows/build-windows.yml
-    with:
-      platform: windows-aarch64
-      msvc-toolset-version: '14.29'
-      msvc-toolset-architecture: 'arm64'
-      make-target: 'hotspot'
-      extra-conf-options: '--openjdk-target=aarch64-unknown-cygwin'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.windows-aarch64 == 'true'
-
-  build-docs:
-    name: docs
-    needs: prepare
-    uses: ./.github/workflows/build-linux.yml
-    with:
-      platform: linux-x64
-      debug-levels: '[ "debug" ]'
-      make-target: 'docs-jdk-bundles'
-      # Make sure we never try to make full docs, since that would require a
-      # build JDK, and we do not need the additional testing of the graphs.
-      extra-conf-options: '--disable-full-docs'
-      gcc-major-version: '10'
-      configure-arguments: ${{ github.event.inputs.configure-arguments }}
-      make-arguments: ${{ github.event.inputs.make-arguments }}
-    if: needs.prepare.outputs.docs == 'true'
-
   ###
   ### Test jobs
   ###
@@ -311,78 +144,34 @@ jobs:
       bootjdk-platform: linux-x64
       runs-on: ubuntu-22.04
 
-  test-macos-x64:
-    name: macos-x64
-    needs:
-      - build-macos-x64
-    uses: ./.github/workflows/test.yml
-    with:
-      platform: macos-x64
-      bootjdk-platform: macos-x64
-      runs-on: macos-13
-      xcode-toolset-version: '14.3.1'
+  # # Remove bundles so they are not misconstrued as binary distributions from the JDK project
+  # remove-bundles:
+  #   name: 'Remove bundle artifacts'
+  #   runs-on: ubuntu-22.04
+  #   if: always()
+  #   needs:
+  #     - build-linux-x64
 
-  test-macos-aarch64:
-    name: macos-aarch64
-    needs:
-      - build-macos-aarch64
-    uses: ./.github/workflows/test.yml
-    with:
-      platform: macos-aarch64
-      bootjdk-platform: macos-aarch64
-      runs-on: macos-14
-      xcode-toolset-version: '15.4'
-
-  test-windows-x64:
-    name: windows-x64
-    needs:
-      - build-windows-x64
-    uses: ./.github/workflows/test.yml
-    with:
-      platform: windows-x64
-      bootjdk-platform: windows-x64
-      runs-on: windows-2019
-
-  # Remove bundles so they are not misconstrued as binary distributions from the JDK project
-  remove-bundles:
-    name: 'Remove bundle artifacts'
-    runs-on: ubuntu-22.04
-    if: always()
-    needs:
-      - build-linux-x64
-      - build-linux-x86-hs
-      - build-linux-x64-hs-nopch
-      - build-linux-x64-hs-zero
-      - build-linux-x64-hs-minimal
-      - build-linux-x64-hs-optimized
-      - build-linux-cross-compile
-      - build-macos-x64
-      - build-macos-aarch64
-      - build-windows-x64
-      - build-windows-aarch64
-      - test-linux-x64
-      - test-macos-x64
-      - test-macos-aarch64
-      - test-windows-x64
-
-    steps:
-      - name: 'Remove bundle artifacts'
-        run: |
-          # Find and remove all bundle artifacts
-          # See: https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28
-          ALL_ARTIFACT_IDS="$(curl -sL \
-              -H 'Accept: application/vnd.github+json' \
-              -H 'Authorization: Bearer ${{ github.token }}' \
-              -H 'X-GitHub-Api-Version: 2022-11-28' \
-              '${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts?per_page=100')"
-          BUNDLE_ARTIFACT_IDS="$(echo "$ALL_ARTIFACT_IDS" | jq -r -c '.artifacts | map(select(.name|startswith("bundles-"))) | .[].id')"
-          for id in $BUNDLE_ARTIFACT_IDS; do
-            echo "Removing $id"
-            curl -sL \
-                -X DELETE \
-                -H 'Accept: application/vnd.github+json' \
-                -H 'Authorization: Bearer ${{ github.token }}' \
-                -H 'X-GitHub-Api-Version: 2022-11-28' \
-                "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/$id" \
-            || echo "Failed to remove bundle"
-          done
+  #   steps:
+  #     - name: 'Remove bundle artifacts'
+  #       run: |
+  #         # Find and remove all bundle artifacts
+  #         FIXME: recover later
+  #         echo "FIXME: don't remove bundles now, recover later"
+  #         # See: https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28
+  #         ALL_ARTIFACT_IDS="$(curl -sL \
+  #             -H 'Accept: application/vnd.github+json' \
+  #             -H 'Authorization: Bearer ${{ github.token }}' \
+  #             -H 'X-GitHub-Api-Version: 2022-11-28' \
+  #             '${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts?per_page=100')"
+  #         BUNDLE_ARTIFACT_IDS="$(echo "$ALL_ARTIFACT_IDS" | jq -r -c '.artifacts | map(select(.name|startswith("bundles-"))) | .[].id')"
+  #         for id in $BUNDLE_ARTIFACT_IDS; do
+  #           echo "Removing $id"
+  #           curl -sL \
+  #               -X DELETE \
+  #               -H 'Accept: application/vnd.github+json' \
+  #               -H 'Authorization: Bearer ${{ github.token }}' \
+  #               -H 'X-GitHub-Api-Version: 2022-11-28' \
+  #               "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/$id" \
+  #           || echo "Failed to remove bundle"
+  #         done
